### ISSUE TITLE
The data doesn't get saved

### ISSUE THREAD

**Issue by kycfeel** [tvandoorn/longvinter-docker-server#2]
**Describe the bug**

**To Reproduce**
Simply run the server with docker-compose, and restart the container afterwards. The data is gone afterwards.

**Expected behavior**
The data is still there and able to continue the game

**Screenshots**

**Server information(please complete the following information):**
 - OS: Ubuntu 20.04
 - Processor: Oracle Cloud Free Tier AMD Server (1vCore)
 - RAM: 1GB

**Additional context**
Thanks for the awesome project. It would be perfect if the data issue get solved.

**Comment by tvandoorn** [comment]
Hello, are you restarting the container immediately after starting it? Because the server only seems to save every x minutes or by certain things triggering a save (not entirely sure what to be honest). If you start the server, join it, leave it after a few seconds and restart the server your changes might not have been saved yet. I also experienced this while testing.

Could you try starting the server, playing for a few minutes (> 5) and restarting the server after 20-30 minutes? By then the server should have saved multiple times and you should see your progress again when you join back.

**Comment by ewrogers** [comment]
Starting with v1.0.2 of the server+client you can now perform a manual save via the Admin Panel menu. Make sure you add your own Steam ID to the list of admins to have access to this. Useful when saving prior to a server upgrade/shutdown.
