### ISSUE TITLE
Unable to connect after 1.0.2 update

### ISSUE THREAD

**Issue by jehoshua02** [tvandoorn/longvinter-docker-server#4]
**Describe the bug**
Was unable to connect after 1.0.2 update.

**To Reproduce**
1. Not sure

**Expected behavior**
Expected to be able to connect after updates to client and server.

**Screenshots**
NA

**Server information(please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04.4 LTS
 - Processor Unsure (Digital Ocean Droplet)
 - RAM 1GB (Runs smooth!)

**Additional context**
Was able to resolve by removing images and containers, recreating the volume, copying `SaveGames` from old volume to new volume, and upping again.

See https://github.com/Uuvana-Studios/longvinter-windows-client/issues/587

**Comment by ewrogers** [comment]
Experiencing the same on my Docker server. Thanks for the heads up on the fix, though that's really curious indeed.

Personally, I think it may be a Git LFS / re-clone / checkout issues (despite nothing seeming wrong). While the auto-update functionality is nice, it also can cause issues like this.

I think it may be better to go with established container release versions instead (i.e. `uvana/longvinter-server:1.0.2`). This way you have a known-good state and potential to rollback versions. The only thing that should need to be mounted would be the config/saves.

**Comment by tvandoorn** [comment]
That's odd, I have not experienced this yet on my two servers. I should note that I am using a directory mount instead of a volume mount though, but I'm not sure if that would be causing this issue. I have just updated my servers to 1.0.2 by restarting them, but they seem to work just fine. I'll keep an eye out for this, but if you figure out why this happens (or have a permanent fix) feel free to add it to this issue or create a pull request.

In terms of auto updating, I figured this would be preferred by users, but it would not be a lot of work to add an environment variable to disable updating on startup. Using images with proper versioning would be nice, but I don't think this should be something that's handled by me. I am planning on transferring ownership of this repo to Uuvana soon (due to lack of time on my side, and to allow others to contribute more easily), so maybe they can set up some form of versioning and upload the images to Docker Hub.

**Comment by jehoshua02** [comment]
There's tradeoffs with both version-pinning and auto-updating strategies and it boils down to a matter of preference, so it'd be nice if both were an option. And I agree, the core developers should be involved in solving this problem. But it's early access, so I'd understand if they held off for a long time on this. Personally, I prefer auto updates, so I'm happy the way it is. It's not much trouble to rebuild once in a while.

**Comment by ewrogers** [comment]
Fair points all around. I know the Uuvana devs have a lot on their plates and only so many hands, don't mind helping where I can. Agreed on making it a preference for auto-updates or not, I don't mind building pinned version containers and publishing them on Docker Hub but I get the convenience.
